### ISSUE TITLE
SECURITY: Enable secure flag when setting cookie

### ISSUE THREAD

**Issue by jbrunemann** [Kaliber/play-basic-authentication-filter#5]
I want to enable the secure flag on the `play-basic-authentication-filter` cookie.

For the default Play session cookie I'm able to define things like:

```
session.secure=true
session.httpOnly=true
```

It would be nice if the same can be set for the `play-basic-authentication-filter` cookie.

**Comment by EECOLOR** [comment]
Would there be any downside to forcing them to use both secure and httpOnly?

**Comment by EECOLOR** [comment]
In favor of #8
